# Generated by Django 5.2 on 2025-05-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shop_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material_type',
            field=models.CharField(choices=[('pla', 'PLA'), ('abs', 'ABS'), ('petg', 'PETG'), ('tpu', 'TPU'), ('nylon', 'Nylon'), ('resin', 'Resin'), ('carbon', 'Carbon Fiber'), ('metal', 'Metal-Infused'), ('wood', 'Wood-Infused'), ('other', 'Other')], default='pla', help_text='Select the recommended printing material', max_length=20),
        ),
    ]
