# Generated by Django 5.2 on 2025-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_user_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (optional)', null=True, upload_to='users/avatars/', verbose_name='Profile Picture'),
        ),
    ]
